deployments:
  DefaultApp:
        filename:
          ./Dockerfile
        port_forwarding:
          80:3000
  Rails_5_2:
        filename:
          ./squash/Dockerfile-Rails5_2
        port_forwarding:
          80:3000
  Ruby252App:
        filename:
          ./squash/Dockerfile-252
        port_forwarding:
          80:3000
  Ruby260App:
        filename:
          ./squash/Dockerfile-260
        port_forwarding:
          80:3000
