FROM ubuntu:18.04
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs rubygems
RUN mkdir /spree
WORKDIR /spree
ADD . /spree

RUN gem 'spree', '~> 3.6.4'
RUN gem 'spree_auth_devise', '~> 3.3'
RUN gem 'spree_gateway', '~> 3.3'

RUN bundle install
RUN bundle exec rake sandbox
CMD ["sh", "docker-entrypoint.sh"]
